# Generated by Django 2.2.6 on 2019-11-17 08:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 8, 38, 37, 384273, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post2',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 8, 38, 43, 619260, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2019, 11, 17, 8, 38, 50, 344142, tzinfo=utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post2',
            name='communityId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communities.Community'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
