# Generated by Django 2.2.6 on 2019-11-24 16:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_datatype_datatypeobject_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatypeobject',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
